### ISSUE TITLE
Prometheus default metric path

### ISSUE THREAD

**Issue by socomsystems** [friends-of-freeswitch/mod_prometheus#12]
The default metric path for Prometheus is .com:port/metrics  In your mods case you have to specify the path in prometheus.yml job as metrics_path: /

**Comment by moises-silva** [comment]
@socomsystems Are you saying `/metrics` does not work? the port should definitely work, and as far as the url path, both should work, the http server is not checking the url at all.

**Comment by socomsystems** [comment]
Hi there @moises-silva. I'm saying it works as is, however the Prometheus scraper convention expectation is to follow the port number up with /metrics.  If you do that in your module, then the scraper code doesn't have to specify the metrics path as "metrics_path: /".  I didn't realize it either until @SuperQ pointed it out to me.  If you look at other Prometheus "metrics" exporters, you'll see most place metrics in a .tld:portn/metrics sub-directory as output.

e.g.  mod_prometheus not exporting to /metrics mean I have to specify to look for the output in / as the root dir.

` - job_name: freeswitch
    metrics_path: /     <--------
    static_configs:
      - targets:
        - "domain.com:6780"
`
If you export to /metrics then it becomes:

` - job_name: freeswitch
    static_configs:
      - targets:
        - "domain.com:6780"
`

**Comment by SuperQ** [comment]
I don't have any system to test this exporter.  I can't tell by the code how the exporter library works.  I don't see any explicit path routing in the listener.  I think @moises-silva is correct, the http server will return metrics for any `GET` request.  So I may have been wrong about needing to change the `metric_path` in the config.

But again, I have no idea how this exporter's HTTP handler works. :)

**Comment by socomsystems** [comment]
`prometheus -h | grep metrics`
...
`   -web.telemetry-path "/metrics"
      Path under which to expose metrics.
`
https://www.screencast.com/t/1SatD49RHqU

HTTP GET: tld:9100 on node_exporter https://www.screencast.com/t/BJbNyiuc

**Comment by moises-silva** [comment]
@socomsystems What I'm saying is *any* path works. You can specify /metrics if you want, or not, it doesn't make a difference.

**Comment by SuperQ** [comment]
Yup, feel free to close this issue.  I was confused when I first looked at the code.

Thanks for making this plugin. :+1:

**Comment by SuperQ** [comment]
Oh, maybe update the `README.rst` to include `/metrics` in the example.

**Comment by moises-silva** [comment]
Heads up @socomsystems , I've changed the port to 9282 as suggested by @SuperQ 

I've also updated the READM.rst to suggest using `/metrics`, even if not strictly required.
