### ISSUE TITLE
Rename module name to mod_prometheus

### ISSUE THREAD

**Issue by ericyan** [friends-of-freeswitch/mod_prometheus#14]
Currently the module name is prefixed with lib, which is unnecessary. The idiomatic way to load the module should be something like this:

```
fscli> load mod_prometheus
```

I understand the lib prefix is due to the way how Cargo works, but in my opinion this quirk should not be passed on to the FreeSWITCH community.

**Comment by ericyan** [comment]
I made a fix here: https://github.com/moises-silva/mod_prometheus/compare/master...ericyan:rename. If you are happy with it, I will send a pull request.

**Comment by moises-silva** [comment]
@ericyan I dabbled a little with cargo wanting to generate the module without the lib prefix but didn't succeed (granted this was a year ago). Doing it on install is fine. Your changes seem good, please open a PR.

Thanks!
